name: CI for Login Test Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-login-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Add current directory to PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run login test only
      run: |
        pytest tests/test_login.py -v --disable-warnings
